project:
  type: website
  output-dir: docs

website:
  title: "LAI Reading Group"
  favicon: lai.svg
  navbar:
    logo: lai.svg
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

