---
title: "About"
---

The website is currently maintained by [Rui Zhang](https://shusheng3927.github.io/) and [Andreas Makris](https://www.linkedin.com/in/andreas-makris-41868b225/). 

Email [Rui](mailto:r.zhang26@lancaster.ac.uk) or [Andreas](mailto:a.makris@lancaster.ac.uk) for any question related to the reading group. 

## Schedule

| Title | Location | Date | Time | Speaker |
|:---------:|:------:|:---:|:---:|:-:|
| Commercial Diffusion Models      | Fylde D31 (and Teams)  | 4 Dec 2024 |   2pm - 3pm   |   Jack    |
| Conditional Diffusions      | Fylde D31 (and Teams)  | 27 Nov 2024 |   2pm - 3pm   |    Tamas   |
| Latent Diffusion      | Fylde D31 (and Teams)  |  20 Nov 2024 |   2pm - 3pm   |   Lanya    |
| U Nets and NN Architectures      | Fylde D31 (and Teams)  |  13 Nov 2024 |   2pm - 3pm   |   Jack    |
| Score Matching      | Fylde D31 (and Teams)  |  6 Nov 2024 |   2pm - 3pm   |   Connie    |
| Derivations of Diffusion Models      | Fylde D31 (and Teams)  | 30 Oct 2024 |   2pm - 3pm   |      Andreas |
| Introduction to Deep Learning      | Fylde D31 (and Teams)  | 23 Oct 2024 |   2pm - 3pm   |    Andreas   |
| A Brief Overview of Diffusion Models      | Fylde D31 (and Teams)  | 16 Oct 2024 |   2.30pm - 3pm   |  Rui     |

## Current Members 

- [Eduard Campillo-Funollet](https://www.lancaster.ac.uk/maths/people/eduard-campillo-funollet)
- [Lloyd Chapman](https://www.lancaster.ac.uk/maths/people/lloyd-chapman)
- [Dan Dodd](https://www.lancaster.ac.uk/sci-tech/about-us/people/daniel-dodd)
- [Miles Elvidge](https://www.research.lancs.ac.uk/portal/en/people/miles-elvidge(4b25b20a-4773-47ee-a688-b093352c961e).html)
- [Paul Fearnhead](https://www.lancaster.ac.uk/maths/people/paul-fearnhead)
- [Yuga Iguchi](https://www.yugaiguchi.com)
- [David Leslie](https://www.lancaster.ac.uk/maths/people/david-leslie)
- [Andreas Makris](https://www.linkedin.com/in/andreas-makris-41868b225/)
- [Henry Moss](https://henrymoss.github.io)
- [Thomas Newman](https://www.lancaster.ac.uk/stor-i-student-sites/thomas-newman/)
- [Chris Nemeth](https://chris-nemeth.github.io/)
- [Tamás P. Papp](https://www.lancaster.ac.uk/stor-i-student-sites/tamas-papp/)
- [Chris Sherlock](https://chrisgsherlock.github.io/)
- [Theodore Tollet](https://www.lancaster.ac.uk/maths/people/theodore-tollet)
- [Jack Trainer](https://www.lancaster.ac.uk/stor-i/about-us/people/jack-trainer)
- [Connie Trojan](https://www.lancaster.ac.uk/stor-i-student-sites/connie-trojan/)
- [Lanya Yang](https://www.lancaster.ac.uk/stor-i-student-sites/lanya-yang/)
- [Rui Zhang](https://shusheng3927.github.io/)
